# -*- coding: utf-8 -*-
"""Consulta_PDF.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aLxdjnAhDhepWsORoCJ1_HTHbOjOW-A2

![texto del vínculo](https://thumbs.dreamstime.com/b/chat-banner-20528092.jpg)

# **CHAT PARA DOCUMENTOS PDF**

## Instalacion de Librerias y Recursos
"""

!pip install openai==0.28.1 langchain==0.0.324 faiss-cpu==1.7.4 PyPDF2==3.0.1 sentence-transformers==2.2.2 python-dotenv==1.0.0 -q

# Importar Librerias y Recursos
from PyPDF2 import PdfReader
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain.embeddings import HuggingFaceEmbeddings
from langchain.vectorstores import FAISS
import os
from langchain.chat_models import ChatOpenAI
from langchain.chains.question_answering import load_qa_chain
from langchain.callbacks import get_openai_callback

"""## Cargue de Documento y creacion de Chunks"""

# Cargar fichero PDF desde el sistema local
pdf_file_path = '/content/4 Machine learning en la industria 4.0.pdf'  # Cambia esto a la ruta de tu archivo PDF
pdf_reader = PdfReader(pdf_file_path)

text = ""
for page in pdf_reader.pages:
    text += page.extract_text()

# Crear chunks
text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=1000,
    chunk_overlap=200,
    length_function=len)

chunks = text_splitter.split_text(text)

"""## Definicion del Embeddings y conexion Api con el LLM"""

# Definicion del modelo y Creacion del Embeddings
embeddings = HuggingFaceEmbeddings(model_name="sentence-transformers/paraphrase-multilingual-mpnet-base-v2")

# Crear embeddings de todo el texto
knowledge_base = FAISS.from_texts(chunks, embeddings)

# Preguntar al documento PDF
os.environ["OPENAI_API_KEY"] = "OPENAI_API_KEY"
llm = ChatOpenAI(model_name='gpt-3.5-turbo')
chain = load_qa_chain(llm, chain_type="stuff")

"""## Consultas al PDF"""

pregunta = "Que es Machine Learning"
# Búsqueda de párrafos similares
docs = knowledge_base.similarity_search(pregunta, 4)
# Utilizar los párrafos similares para darle contexto a ChatGPT
respuesta = chain.run(input_documents=docs, question=pregunta)
print(f"Respuesta ChatGPT: {respuesta}")

with get_openai_callback() as cb:
    response = chain.run(input_documents=docs, question=pregunta)
    print(cb)